### ISSUE TITLE
make normal css so its available for non-plugin users

### ISSUE THREAD

**Issue by sprmcell** [yuwui/powercord-greentext#7]
would be a major enhancement, even its a different repo just so it can work on other clients that dont have the plugin

**Comment by yuwui** [comment]
what

**Comment by sprmcell** [comment]
this repo only works with the plugin right? making it in normal css or giving the css snippet to make it work on normal themes would be cool

**Comment by yuwui** [comment]
I don't really get what you mean. this plugin is not css only, it wraps the message elements in wrapper elements so the css can apply to them. it needs powercord in order to function.
you are free to port this to any other client mod, it shouldn't be too hard, but a css-only option is beyond the scope of what css can do.
